# mypy.ini

[mypy]
python_version = 3.8           # Set Python version for type checking
ignore_missing_imports = True  # Ignore errors for missing imports
warn_unused_ignores = True     # Warn if there are unnecessary 'type: ignore' comments
disallow_untyped_defs = True   # Disallow functions without type annotations
disallow_incomplete_defs = True  # Require complete type hints for functions with some annotations
check_untyped_defs = True      # Analyze function bodies even if they don't have type annotations
no_implicit_optional = True    # Do not treat missing annotations as Optional
warn_return_any = True         # Warn when returning a value of type Any
warn_redundant_casts = True    # Warn about casts that are not necessary
warn_unused_configs = True     # Warn about any unused config options
strict_equality = True         # Disallow equality checks between unrelated types