### Healthcheck
GET {{ endpoint }}
Content-Type: application/json

### Add a card for access
POST {{ endpoint }}/card/add
Content-Type: application/json
X-Environment: {{ environment }}

{
  "number": "TEST1234567890",
  "name": "test_card",
  "devices": [
    "test_card_reader"
  ],
  "ttl": 36000,
  "persist": false
}

### Identify successfully used JSON
POST {{ endpoint }}/identify/json
Content-Type: application/json
X-Environment: {{ environment }}
X-Device-SN: test_card_reader

{
  "card_number": "TEST1234567890"
}

### Identify failure used JSON
POST {{ endpoint }}/identify/json
Content-Type: application/json
X-Environment: {{ environment }}
X-Device-SN: test_card_reader

{
  "card_number": "WRONG_CARD1234567890"
}

### API for Vguang M350
POST {{ endpoint }}/identify/vguang-m350/test_card_reader
Content-Type: text/plain

TEST1234567890
