### Healthcheck
GET {{ endpoint }}
Content-Type: application/json

### ** Add a card for access **
POST {{ endpoint }}/card/add
Content-Type: application/json
X-Environment: {{ environment }}

{
  "number": "6B06C2A25E99C68EDCBE",
  "name": "test_card",
  "devices": [
    "etoehotel-101",
    "etoehotel-102",
    "etoehotel-103",
    "etoehotel-104",
    "etoehotel-201",
    "etoehotel-202",
    "etoehotel-203",
    "etoehotel-204",
    "etoehotel-205",
    "etoehotel-206",
    "etoehotel-301",
    "etoehotel-302",
    "etoehotel-303",
    "etoehotel-304",
    "etoehotel-305",
    "test-555"
  ],
  "start_at": "",
  "end_at": "",
  "ttl": 600000000,
  "persist": true,
  "owner_client_id": "anonymous"
}

### Get Cards by owner_client_id
GET {{ endpoint }}/owner/anonymous
Content-Type: text/plain


### ** Identify: API for Vguang M350 **
### etoehotel's code scanner actually uses this endpoint
### The card number is transmitted to the server as a flat text. If the code=0000 is returned, the relay will be notified to open the door lock.
POST {{ endpoint }}/identify/vguang-m350/test-555
Content-Type: text/plain

74165B29


### Identify: successfully used JSON
POST {{ endpoint }}/identify/json
Content-Type: application/json
X-Environment: {{ environment }}
X-Device-SN: test_card_reader

{
  "card_number": "TEST1234567890kkk"
}

### Identify: failure used JSON
POST {{ endpoint }}/identify/json
Content-Type: application/json
X-Environment: {{ environment }}
X-Device-SN: test_card_reader

{
  "card_number": "WRONG_CARD1234567890"
}