### Healthcheck
GET {{ endpoint }}
Content-Type: application/json

### ** Add a card for access **
POST {{ endpoint }}/card/add
Content-Type: application/json
X-Environment: {{ environment }}
#Authorization: Bearer {{ token }}

{
  "number": "test00000101180610",
  "name": "test_card",
  "devices": [
    "etoehotel-101"
  ],
  "start_at": "2025-04-14T12:35:00+09:00",
  "ttl": 360,
  "persist": false,
  "owner_client_id": "anonymous"
}

### Get Cards by owner_client_id
GET {{ endpoint }}/owner/anonymous
Content-Type: text/plain


### ** Identify: API for Vguang M350 **
### etoehotel's code scanner actually uses this endpoint
### The card number is transmitted to the server as a flat text. If the code=0000 is returned, the relay will be notified to open the door lock.
POST {{ endpoint }}/identify/vguang-m350/etoehotel-101
Content-Type: text/plain

test-----101-18-00-05


### Identify: successfully used JSON
POST {{ endpoint }}/identify/json
Content-Type: application/json
X-Environment: {{ environment }}
X-Device-SN: test_card_reader

{
  "card_number": "TEST1234567890kkk"
}

### Identify: failure used JSON
POST {{ endpoint }}/identify/json
Content-Type: application/json
X-Environment: {{ environment }}
X-Device-SN: test_card_reader

{
  "card_number": "WRONG_CARD1234567890"
}